services:
  # Backend API Server (Development)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: virallens-backend-dev
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development
      PORT: 4000
      # MONGODB_URI will be loaded from .env file (MongoDB Atlas)
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "4000:4000"
    networks:
      - virallens-dev-network
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App (Development)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: virallens-frontend-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:4000
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    networks:
      - virallens-dev-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  virallens-dev-network:
    driver: bridge
