services:
  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: virallens-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 4000
      # MONGODB_URI will be loaded from .env file (MongoDB Atlas)
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "4000:4000"
    networks:
      - virallens-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: virallens-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:80"
    networks:
      - virallens-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  virallens-network:
    driver: bridge
