services:
  - type: web
    name: virallens
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://virallens.onrender.com
      - key: COOKIE_DOMAIN
        value: virallens.onrender.com
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_SAME_SITE
        value: none
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: meta-llama/llama-3.2-3b-instruct:free
