version: '3.8'

services:
  # MongoDB service (same as production)
  mongodb:
    image: mongo:7.0
    container_name: virallens-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: virallens
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - virallens-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Node.js API server (development mode)
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: virallens-api-dev
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://app_user:app_password@mongodb:27017/virallens?authSource=virallens
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - virallens-dev-network
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_dev_data:
    driver: local

networks:
  virallens-dev-network:
    driver: bridge
